version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - backend
    depends_on:
      - php

  php:
    build: .
    hostname: php
    volumes:
      - .:/var/www
    networks:
      - backend
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${DB_DATABASE}"
      - MYSQL_USER="${DB_USERNAME}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
    volumes:
      - data-volume:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data-volume:
    driver: local
